run:
  go: '1.23'
linters:
  enable-all: true
  disable:
    - gofmt
    - gci
    - exhaustruct
    - varnamelen
    - depguard

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  cyclop:
    min-complexity: 20
    max-complexity: 30
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gomoddirectives:
    # List of allowed `replace` directives. Default is empty.
    replace-allow-list:
      - bou.ke/monkey
  lll:
    line-length: 140
  funlen:
    lines: 130
    statements: 70
  nestif:
    # minimal complexity of if statements to report
    min-complexity: 6
  gocognit:
    min-complexity: 35

issues:
  exclude-use-default: false
  exclude:
    # gochecknoglobals: allow version variable
    - "`version` is a global variable"
